export const authorList = [
	"Dani Long",
	"Matt Alvarado",
	"Solomon Bloch",
	"Jeff Chesanek",
	"Ryan D'entrement",
	"Lindsey Fletcher",
	"Jake Price",
	"Kelsey Rustin",
	"Margo Stepka",
	"Rahul Kasibhatla",
	"Rui Wang",
	"Sarah Tran",
	"James Wolerson",
];